### PR TITLE
Add TR Locales

### PR DESCRIPTION
**Pull request by mikropsoft**
Sorry for not translating it via Transifex. It works better this way. It would be great if you could transfer this.

### CODE REVIEW

**Comment by mikropsoft** [comment]
> Thanks so much! I'm able to add a translation file manually to Transifex, so this should work! Please make future additions through Transifex because that's a lot easier to manage, so please create an account there and look for new strings from time to time (or I'm sure you can turn on email notifications for that). With every new feature or improvement the chance is high that I added new strings or changed others, these changes should be a lot easier to spot for you in Transifex.

Actually I use crowdin actively but I have never tried transifex, I will open an account in the next updates, thank you.

**Comment by mikropsoft** [comment]
> Thanks so much! I'm able to add a translation file manually to Transifex, so this should work! Please make future additions through Transifex because that's a lot easier to manage, so please create an account there and look for new strings from time to time (or I'm sure you can turn on email notifications for that). With every new feature or improvement the chance is high that I added new strings or changed others, these changes should be a lot easier to spot for you in Transifex.

Actually I use crowdin actively but I have never tried transifex, I will open an account in the next updates, thank you.

**Comment by patzly** [comment]
https://app.transifex.com/patzly/tack-android/translate/#/tr

You can see on the page above that there are a few strings missing for Wear OS. Tack has a separate Wear OS app for smartwatches and despite many strings are shared and identical, there are a few that are different. So please consider creating an account to translate the few strings left. That would be awesome!

**Comment by patzly** [comment]
I have added new strings on Transifex: https://app.transifex.com/patzly/tack-android/language/tr/
You can translate them there, so I will close this request. The update with your translations is coming soon, thanks again!

**Pull request closed without merging**
